---
version: '2.1'
services:
  sender:
    build: sender
    depends_on:
      receiver:
        condition: service_healthy
    environment:
      RECEIVER_HOSTNAME: receiver
    volumes:
      - ./json_data:/tmp/json_data
  receiver:
    build: receiver
    ports:
      - "5555:5555"
    volumes:
      - ./xml_data:/tmp/xml_data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5555"]
      interval: 2s
      timeout: 3s
      retries: 3

